version: '3.8'

services:
  maria-master:
    image: mariadb:10
    container_name: maria-master
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: Asia/Seoul



  maria-slave:
    image: mariadb:10
    container_name: maria-slave
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Seoul


  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"