server:
  port: 9010
  servlet:
    context-path: "/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: one

  profiles:
    include:
      - security

  datasource:
    url: jdbc:mariadb://localhost:3306/one
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

#  datasource:
#    master:
#      hikari:
#        driver-class-name: org.mariadb.jdbc.Driver
#        jdbc-url: jdbc:mariadb://localhost:3306/one
#        username: root
#        password: password
#    slave:
#      hikari:
#        driver-class-name: org.mariadb.jdbc.Driver
#        jdbc-url: jdbc:mariadb://localhost:3307/
#        username: root
#        password: password


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

#  flyway:
#    enabled: true # flyway를 사용하겠다는 설정
#    baseline-on-migrate: true # 버전 정보를 flyway_schema_history라는 테이블에서 자동으로 생성
#    url: jdbc:mariadb://localhost:3306
#    user: 'root'
#    password: 'password'

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: root
      password: password
      uri: mongodb://localhost:27018/db


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE

client:
  url: "http://apis.data.go.kr/1262000/CountryKorTradeService2"
  timeout: 10000
  read-time: 10
  write-time: 10