spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "615491681676-4tte5t2r3qqltnpdgscrj6vbq4cth9r6.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - profile
              - email


jwt:
  secret: "1q2w3e4r5t6y7u8i9o0p!@#$%^&*()QWERTYUIOP"
  validTime: 300000

recaptcha:
  secret_key: "6LczQxcmAAAAAHPOhl5mPsNSwfaui-Er9sDkZ5fD"
  verify_url: "https://www.google.com/recaptcha/api/siteverify"